# Generated by Django 4.2.9 on 2025-08-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mark_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='mark_for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
